---
- name: Install MSYS2, Due to github-actions being dumb this has to be on the root of the drive
  chocolatey.chocolatey.win_chocolatey:
    name: msys2
    package_params: /InstallDir="{{ drive }}:\msys64"
    state: present

- name: Configure packages
  ansible.builtin.import_tasks: configure_msys2_packages.yml
