---
- name: Installing XLink Handheld Assistant build environment
  hosts: win

  tasks:
    - name: Grab variables
      ansible.builtin.include_vars:
        file: vars.yml

    - name: Install Base
      ansible.builtin.import_tasks: install_base.yml
      when: install_base

    - name: Install Runner
      ansible.builtin.import_tasks: install_runner.yml
      when: install_runner

    - name: Install Development Environment
      ansible.builtin.import_tasks: install_devenv.yml
      when: install_devenv
